<?php
/**
 * Plugin specific util functinos.
 *
 * @package ElasticPressLabs
 */

namespace ElasticPressLabs\Utils;

/**
 * List of reserved words in JavaScript
 *
 * @see https://www.w3schools.com/js/js_reserved.asp
 * @return string
 */
function get_js_reserved_words() {
	return [
		'abstract',
		'arguments',
		'await',
		'boolean',
		'break',
		'byte',
		'case',
		'catch',
		'char',
		'class',
		'const',
		'continue',
		'debugger',
		'default',
		'delete',
		'do',
		'double',
		'else',
		'enum',
		'eval',
		'export',
		'extends',
		'false',
		'final',
		'finally',
		'float',
		'for',
		'function',
		'goto',
		'if',
		'implements',
		'import',
		'instanceof',
		'int',
		'interface',
		'let',
		'long',
		'native',
		'new',
		'null',
		'package',
		'private',
		'protected',
		'public',
		'return',
		'short',
		'static',
		'super',
		'switch',
		'synchronized',
		'throw',
		'throws',
		'transient',
		'true',
		'try',
		'typeof',
		'var',
		'void',
		'volatile',
		'while',
		'with',
		'yield',
		'abstract',
		'boolean',
		'byte',
		'char',
		'double',
		'final',
		'float',
		'goto',
		'int',
		'long',
		'native',
		'short',
		'synchronized',
		'throws',
		'transient',
		'volatile',
		'Array',
		'Date',
		'eval',
		'function',
		'hasOwnProperty',
		'Infinity',
		'isFinite',
		'isNaN',
		'isPrototypeOf',
		'length',
		'Math',
		'NaN',
		'name',
		'Number',
		'Object',
		'prototype',
		'String',
		'toString',
		'undefined',
		'valueOf',
		'getClass',
		'java',
		'JavaArray',
		'javaClass',
		'JavaObject',
		'JavaPackage',
		'alert',
		'all',
		'anchor',
		'anchors',
		'area',
		'assign',
		'blur',
		'button',
		'checkbox',
		'clearInterval',
		'clearTimeout',
		'clientInformation',
		'close',
		'closed',
		'confirm',
		'constructor',
		'crypto',
		'decodeURI',
		'decodeURIComponent',
		'defaultStatus',
		'document',
		'element',
		'elements',
		'embed',
		'embeds',
		'encodeURI',
		'encodeURIComponent',
		'escape',
		'event',
		'fileUpload',
		'focus',
		'form',
		'forms',
		'frame',
		'innerHeight',
		'innerWidth',
		'layer',
		'layers',
		'link',
		'location',
		'mimeTypes',
		'navigate',
		'navigator',
		'frames',
		'frameRate',
		'hidden',
		'history',
		'image',
		'images',
		'offscreenBuffering',
		'open',
		'opener',
		'option',
		'outerHeight',
		'outerWidth',
		'packages',
		'pageXOffset',
		'pageYOffset',
		'parent',
		'parseFloat',
		'parseInt',
		'password',
		'pkcs11',
		'plugin',
		'prompt',
		'propertyIsEnum',
		'radio',
		'reset',
		'screenX',
		'screenY',
		'scroll',
		'secure',
		'select',
		'self',
		'setInterval',
		'setTimeout',
		'status',
		'submit',
		'taint',
		'text',
		'textarea',
		'top',
		'unescape',
		'untaint',
		'window',
		'onblur',
		'onclick',
		'onerror',
		'onfocus',
		'onkeydown',
		'onkeypress',
		'onkeyup',
		'onmouseover',
		'onload',
		'onmouseup',
		'onmousedown',
		'onsubmit',
		'jQuery',
	];
}

/**
 * Get asset info from extracted asset files
 *
 * @param string $slug Asset slug as defined in build/webpack configuration
 * @param string $attribute Optional attribute to get. Can be version or dependencies
 * @return string|array
 */
function get_asset_info( $slug, $attribute = null ) {
	if ( file_exists( ELASTICPRESS_LABS_PATH . 'dist/js/' . $slug . '.asset.php' ) ) {
		$asset = require ELASTICPRESS_LABS_PATH . 'dist/js/' . $slug . '.asset.php';
	} elseif ( file_exists( ELASTICPRESS_LABS_PATH . 'dist/css/' . $slug . '.asset.php' ) ) {
		$asset = require ELASTICPRESS_LABS_PATH . 'dist/css/' . $slug . '.asset.php';
	} else {
		return null;
	}

	if ( ! empty( $attribute ) && isset( $asset[ $attribute ] ) ) {
		return $asset[ $attribute ];
	}

	return $asset;
}
